### ISSUE TITLE
Optional argument 'repIndex' not optional

### ISSUE THREAD

**Issue by erinshellman** [eg-r/sights#1]
Hey there,

I'm using the scatter plots and getting errors when I don't supply the optional `repIndex` argument:

```{r}
plotScatter(plotMatrix = input[ , 4:5])
Error in plotScatter(plotMatrix = input[, 4:5]) : 
  argument "repIndex" is missing, with no default
```

**Comment by eg-r** [comment]
Hello! Thanks for pointing this out! It's true, it's not optional in `plotScatter`, that's an error in the description. 
`repIndex` is only optional in `plotBox`. For all other functions, it needs to be defined.  
> `repIndex` Vector of labels indicating replicate group. Each index in the vector matches the corresponding column of plotMatrix.

**Comment by eg-r** [comment]
Updated in March 2018, will be reflected in the next version.
